namespace PonPon.Modules.Ordering.Application.Features.Orders.GetOrderById;

public sealed record OrderDetailResponse(
    Guid Id,
    long ZortOrderId,
    string Number,
    long? ZortCustomerId,
    string? CustomerCode,
    string? CustomerName,
    string? CustomerIdNumber,
    string? CustomerEmail,
    string? CustomerPhone,
    string? CustomerAddress,
    string Status,
    string PaymentStatus,
    decimal Amount,
    decimal VatAmount,
    decimal ShippingAmount,
    decimal PaymentAmount,
    decimal DiscountAmount,
    string? ShippingChannel,
    string? ShippingName,
    string? ShippingAddress,
    string? ShippingPhone,
    string? TrackingNo,
    DateTime? OrderDate,
    DateTime? ShippingDate,
    string? Reference,
    string? Description,
    string SalesChannel,
    string? IntegrationCustomerId,
    string? IntegrationCustomer,
    string? WarehouseCode,
    bool IsCod,
    string? Currency,
    DateTime? ZortCreatedAt,
    DateTime? ZortUpdatedAt,
    DateTime LastSyncedAt,
    IReadOnlyCollection<OrderItemResponse> Items,
    IReadOnlyCollection<OrderPaymentResponse> Payments);

public sealed record OrderItemResponse(
    Guid Id,
    long? ZortProductId,
    string Sku,
    string Name,
    decimal Quantity,
    string? UnitText,
    decimal PricePerUnit,
    string? Discount,
    decimal DiscountAmount,
    decimal TotalPrice,
    int ProductType,
    long? BundleId,
    string? BundleCode,
    string? BundleName);

public sealed record OrderPaymentResponse(
    Guid Id,
    long? ZortPaymentId,
    string Name,
    decimal Amount,
    DateTime? PaymentDateTime);
