// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PonPon.Modules.Identity.Infrastructure.Persistence;

#nullable disable

namespace PonPon.Modules.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260626080000_AddCustomerAddresses")]
    partial class AddCustomerAddresses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
