// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PonPon.Modules.Shipping.Infrastructure.Persistence;

#nullable disable

namespace PonPon.Modules.Shipping.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20260630100000_AddUniqueShippingShipmentOrderId")]
    partial class AddUniqueShippingShipmentOrderId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
