// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PonPon.Modules.Promotion.Infrastructure;

#nullable disable

namespace PonPon.Modules.Promotion.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260706120000_AddCouponBulkGenerationJobs")]
    partial class AddCouponBulkGenerationJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("promotion")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCombineWithFlashSale")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaximumDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MaximumTotalUses")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumUsesPerCustomer")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("coupons", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CouponId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("coupon_audit_logs", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponBulkGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedByUserType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("CampaignId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("coupon_bulk_generation_jobs", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IsActive", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("coupon_campaigns", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("coupon_conditions", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponCustomerScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("CustomerId");

                    b.ToTable("coupon_customer_scopes", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ZortCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku");

                    b.HasIndex("VariantId");

                    b.HasIndex("ZortCategoryId");

                    b.ToTable("coupon_scopes", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("CouponId", "CustomerId", "IsReleased");

                    b.ToTable("coupon_usages", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCombineWithFlashSale")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanStackWithCoupon")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanStackWithPromotions")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaximumDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MaximumTotalUses")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumUsesPerCustomer")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("IsActive", "StartsAtUtc", "EndsAtUtc", "Priority");

                    b.ToTable("promotions", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("promotion_conditions", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionCustomerScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PromotionId");

                    b.ToTable("promotion_customer_scopes", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionScheduleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("EndsAtLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("StartsAtLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Type", "DayOfWeek", "DayOfMonth");

                    b.ToTable("promotion_schedule_rules", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsExclude")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Sku");

                    b.HasIndex("VariantId");

                    b.ToTable("promotion_scopes", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "PromotionId")
                        .IsUnique();

                    b.HasIndex("PromotionId", "CustomerId", "IsReleased");

                    b.ToTable("promotion_usages", "promotion");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Coupon", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.CouponCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponBulkGenerationJob", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.CouponCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponCondition", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Coupon", null)
                        .WithMany("Conditions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponCustomerScope", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Coupon", null)
                        .WithMany("CustomerScopes")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponScope", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Coupon", null)
                        .WithMany("Scopes")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.CouponUsage", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Promotion", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.CouponCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionCondition", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Promotion", null)
                        .WithMany("Conditions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionCustomerScope", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Promotion", null)
                        .WithMany("CustomerScopes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionScheduleRule", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Promotion", null)
                        .WithMany("ScheduleRules")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionScope", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Promotion", null)
                        .WithMany("Scopes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.PromotionUsage", b =>
                {
                    b.HasOne("PonPon.Modules.Promotion.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Coupon", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("CustomerScopes");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("PonPon.Modules.Promotion.Domain.Promotion", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("CustomerScopes");

                    b.Navigation("ScheduleRules");

                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
