// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PonPon.Modules.Promotion.Infrastructure;

#nullable disable

namespace PonPon.Modules.Promotion.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260707060536_AddCouponClaims")]
    partial class AddCouponClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
