<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PonPon.Shared\PonPon.Shared.csproj" />
    <ProjectReference Include="..\PonPon.Modules.Catalog\PonPon.Modules.Catalog.csproj" />
    <ProjectReference Include="..\PonPon.Modules.Promotion\PonPon.Modules.Promotion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
    <UserSecretsId>7ab09d04-bd3a-496d-bbff-fd8ab23a3cf1</UserSecretsId>
  </PropertyGroup>

</Project>
